/**
build.gradle

Copyright 2014 Crown copyright (c)
Land Information New Zealand and the New Zealand Government.
All rights reserved

This program is released under the terms of the new BSD license. See the
LICENSE file for more information.
 */
 
 buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        //mvnrepository { url "https://mvnrepository.com/artifact/" }
        //maven { url "https://plugins.gradle.org/m2/" }
    }

    dependencies {
        classpath "org.postgresql:postgresql:9.4-1206-jdbc42"
        classpath 'com.bmuschko:gradle-cargo-plugin:2.7.1'
        //pygradle
        //classpath "gradle.plugin.com.linkedin.pygradle:pygradle-plugin:0.3.24"
        //debpackage
        //classpath 'com.netflix.nebula:gradle-ospackage-plugin:1+'
        //junit 
        //classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.0-M4'

    }
}


plugins {
  //id "com.linkedin.python" version "0.3.24"
  //id 'com.linkedin.python-sdist' version '0.9.11'
  id("com.pswidersk.python-plugin") version "2.4.0"
  id 'eclipse'
}

pythonPlugin {
    pythonVersion.set("3.9.5")
    condaVersion.set("23.10.0")
    condaInstaller.set("Miniconda3")
    condaRepoUrl.set("https://anaconda.org/conda-forge")
}

ext {
    postgresqlJDBCVersion = '42.6.0'
    postgresqlApiVersion = '42.6.0'
    postGISApiVersion = '2021.1.0'
    jakartaServletApiVersion = '6.+'
    catalinaVersion = '10.1.2'
    tomcatVersion = '10.1.2'
    jakartaJSONAPIVersion = '2.1.3'
    jakartaJSONVersion = '2.01'
    junitVersion = '5.10.1'
    jmockVersion = '2.12.0'
    jsoupVersion = '1.16.2'
    py4jVersion =  '0.10.9.7'
    cargoVersion = '2.4'
}

apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'com.bmuschko.cargo'
//apply plugin: "com.linkedin.python"
//apply plugin: "nebula.deb"

version = '0.2'
sourceCompatibility = '1.8'

def webContext = 'ab'
def warDir = 'build/libs/'
def warName = 'ab.war'
def packName = 'AdminBoundaryDownloader'
def packVersion = '0.2'

//packages the uploader component linz-admin-boundaries-uploader into src/main/webapp

task copyscripts(type: Copy) {
     //dependsOn test
     //from('scripts') {
     from('../linz-admin-boundaries-uploader/labu') {
         include '**/*.py'
         include '**/*.ini'
         include '**/*.properties'
         include '**/*.template'
     }
     into 'src/main/webapp/WEB-INF/scripts'
}

war {
    dependsOn copyscripts
    //exclude 'src/test/java/nz/govt/linz/AdminBoundariesUITest/**'
    manifest {
        attributes 'Implementation-Title': 'LINZ Admin Boundaries Downloader',
            'Implementation-Version': version
    }
    archiveFileName = warName
}

task cargosetup {
    print "> Server ${remoteHost}\n"
    dependsOn war
	cargo {
	    containerId = 'tomcat10x'
	    port = 8080
	
	    deployable {
	        file = file("./"+warDir+warName)
	        context = webContext
	    }
	    print "> warfile ${warDir}${warName}\n"
	    
	    remote {
	       protocol = "${remoteProtocol}"
	       hostname = "${remoteHost}"
	       username = "${remoteUser}"
	       password = "${remotePass}"
	    }
	}    
}

/*task flake8 (overwrite: true){
   ignore = "E3"
}*/

task redeploy {
    dependsOn cargosetup, cargoRedeployRemote
}

task deploy {
    dependsOn cargosetup, cargoDeployRemote
}

task undeploy {
    dependsOn cargosetup, cargoUndeployRemote
}

repositories {
    mavenCentral()
    //pyGradlePyPi() // Removed this as pyGradle is no longer supported for the targetting python version (3.9.5)
    ivy { url "../../ivy/repository" }
    //flatDir name: "local", dirs: "~/ivy/repository"
    //flatDir name: "local", dirs: "~/git/aims/build/libs"
}

dependencies {
	//NB nz.govt.linz are local ivy repo workarounds. Replace as needed
	//compile files("~/git/aims/build/libs/aims-dev.war")
    providedCompile "jakarta.servlet:jakarta-servlet-api:$jakartaServletApiVersion"
    providedCompile "org.apache.tomcat:tomcat-catalina:$catalinaVersion" 
    providedCompile "org.apache.tomcat:tomcat-util:$tomcatVersion"
    providedCompile "org.postgresql:postgresql:$postgresqlJDBCVersion"
    providedRuntime "net.postgis:postgis-jdbc:$postGISApiVersion"
    providedRuntime "org.postgresql:postgresql:$postgresqlApiVersion"
    implementation "net.sf.py4j:py4j:$py4jVersion"
    implementation "jakarta.json:jakarta.json-api:$jakartaJSONAPIVersion"
    implementation "org.glassfish:jakarta.json:$jakartaJSONVersion"
    testImplementation "org.junit.jupiter:junit-jupiter-api:$junitVersion" 
    testImplementation "org.jmock:jmock:$jmockVersion" 
    testImplementation "org.jsoup:jsoup:$jsoupVersion"
    /*
    python "pypi:pexpect:4.2.1"
    python "pypi:psycopg2:2.6.2"
    python "pypi:GDAL:2.4.0"
    */
    /*
    //test "nz.govt.linz:psycopg2:2.6.2"
    test "nz.govt.linz:psycopg2:2.8.5"
    test "nz.govt.linz:pexpect:4.2.1"
    //test "nz.govt.linz:pygdal:2.2.1.3"
    test "nz.govt.linz:pygdal:3.1.2.6"
    //test "org.gdal:gdal:2.4.0"
    //test "nz.govt.linz:ptyprocess:0.5.1"
    test "nz.govt.linz:ptyprocess:0.6.0"
    */
}


